### ISSUE TITLE
1.21 Error on Launch

### ISSUE THREAD

**Issue by Etanarvazac** [Dplayend/Merge-Enchantments#17]
I know it's not yet been updated, but wanted to provide the error and crash report for it. Used `ini` to help readability.

```ini
[07/30/2024 17:57:02 PM] [Datafixer Bootstrap/INFO] 226 Datafixer optimizations took 492 milliseconds
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48)
[07/30/2024 17:57:07 PM] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[07/30/2024 17:57:07 PM] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[07/30/2024 17:57:07 PM] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[07/30/2024 17:57:07 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[07/30/2024 17:57:07 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[07/30/2024 17:57:07 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[07/30/2024 17:57:07 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[07/30/2024 17:57:07 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[07/30/2024 17:57:07 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_9304.<clinit>(class_9304.java:36)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_9334.method_57899(class_9334.java:93)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_9334.method_57906(class_9334.java:276)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_9334.<clinit>(class_9334.java:93)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:195)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:185)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_1792.<init>(class_1792.java:98)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_1739.<init>(class_1739.java:12)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_1802.<clinit>(class_1802.java:43)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_6089.method_9530(class_6089.java:64)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_4970.method_9549(class_4970.java:355)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_2358.method_10199(class_2358.java:336)
[07/30/2024 17:57:07 PM] 	at net.minecraft.class_2966.method_12851(class_2966.java:52)
[07/30/2024 17:57:07 PM] 	at net.minecraft.client.main.Main.main(Main.java:130)
[07/30/2024 17:57:07 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[07/30/2024 17:57:07 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[07/30/2024 17:57:07 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/30/2024 17:57:07 PM] [main/ERROR] Mixin apply for mod merenc failed merenc.mixins.json:MixEnchantment from mod merenc -> net.minecraft.class_1887: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on canCombine could not find any targets matching 'Lnet/minecraft/class_1887;method_8188(Lnet/minecraft/class_1887;)Z' in net/minecraft/class_1887. Using refmap merenc-refmap.json [INJECT_PREPARE Applicator Phase -> merenc.mixins.json:MixEnchantment from mod merenc -> Prepare Injections -> handler$bpp000$merenc$canCombine(Lnet/minecraft/class_1887;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse ->  -> Validate Targets]
[07/30/2024 17:57:08 PM] 	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:140)
[07/30/2024 17:57:08 PM] 	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:135)
[07/30/2024 17:57:08 PM] 	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:527)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_6396.method_37123(class_6396.java:70)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_310.method_37274(class_310.java:2547)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_310.method_22681(class_310.java:2517)
[07/30/2024 17:57:08 PM] 	at net.minecraft.client.main.Main.main(Main.java:210)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/30/2024 17:57:08 PM] [main/WARN] Failed to get system info for GL Caps
[07/30/2024 17:57:08 PM] ---- Minecraft Crash Report ----
[07/30/2024 17:57:08 PM] // I bet Cylons wouldn't have this problem.
[07/30/2024 17:57:08 PM] 
[07/30/2024 17:57:08 PM] Time: 2024-07-30 17:57:08
[07/30/2024 17:57:08 PM] Description: Bootstrap
[07/30/2024 17:57:08 PM] 
[07/30/2024 17:57:08 PM] java.lang.ExceptionInInitializerError
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_9334.method_57899(class_9334.java:93)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_9334.method_57906(class_9334.java:276)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_9334.<clinit>(class_9334.java:93)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:195)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:185)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1792.<init>(class_1792.java:98)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1739.<init>(class_1739.java:12)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1802.<clinit>(class_1802.java:43)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_6089.method_9530(class_6089.java:64)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970.method_9549(class_4970.java:355)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_2358.method_10199(class_2358.java:336)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_2966.method_12851(class_2966.java:52)
[07/30/2024 17:57:08 PM] 	at net.minecraft.client.main.Main.main(Main.java:130)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/30/2024 17:57:08 PM] Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1887 failed
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[07/30/2024 17:57:08 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_9304.<clinit>(class_9304.java:36)
[07/30/2024 17:57:08 PM] 	... 21 more
[07/30/2024 17:57:08 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[07/30/2024 17:57:08 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[07/30/2024 17:57:08 PM] 	... 26 more
[07/30/2024 17:57:08 PM] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [merenc.mixins.json:MixEnchantment from mod merenc] from phase [DEFAULT] in config [merenc.mixins.json] FAILED during APPLY
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[07/30/2024 17:57:08 PM] 	... 29 more
[07/30/2024 17:57:08 PM] Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on canCombine could not find any targets matching 'Lnet/minecraft/class_1887;method_8188(Lnet/minecraft/class_1887;)Z' in net/minecraft/class_1887. Using refmap merenc-refmap.json [INJECT_PREPARE Applicator Phase -> merenc.mixins.json:MixEnchantment from mod merenc -> Prepare Injections -> handler$bpp000$merenc$canCombine(Lnet/minecraft/class_1887;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse ->  -> Validate Targets]
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48)
[07/30/2024 17:57:08 PM] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[07/30/2024 17:57:08 PM] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[07/30/2024 17:57:08 PM] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
[07/30/2024 17:57:08 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[07/30/2024 17:57:08 PM] 	... 29 more
[07/30/2024 17:57:08 PM] 
[07/30/2024 17:57:08 PM] 
[07/30/2024 17:57:08 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[07/30/2024 17:57:08 PM] ---------------------------------------------------------------------------------------
[07/30/2024 17:57:08 PM] 
[07/30/2024 17:57:08 PM] -- Head --
[07/30/2024 17:57:08 PM] Thread: main
[07/30/2024 17:57:08 PM] Stacktrace:
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_9334.method_57899(class_9334.java:93)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_9334.method_57906(class_9334.java:276)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_9334.<clinit>(class_9334.java:93)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:195)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:185)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1792.<init>(class_1792.java:98)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1739.<init>(class_1739.java:12)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_1802.<clinit>(class_1802.java:43)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_6089.method_9530(class_6089.java:64)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970.method_9549(class_4970.java:355)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_2358.method_10199(class_2358.java:336)
[07/30/2024 17:57:08 PM] 	at net.minecraft.class_2966.method_12851(class_2966.java:52)
[07/30/2024 17:57:08 PM] 
[07/30/2024 17:57:08 PM] -- Initialization --
[07/30/2024 17:57:08 PM] Details:
[07/30/2024 17:57:08 PM] 	Modules: 
[07/30/2024 17:57:08 PM] 		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		GDI32.dll:GDI Client DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		MpOav.dll:IOfficeAntiVirus Module:4.18.24060.7 (47d4bdd9064bc68e82ed85dd3a432e84e907a9be):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		SHELL32.dll:Windows Shell Common Dll:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
[07/30/2024 17:57:08 PM] 		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] 		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[07/30/2024 17:57:08 PM] #@!@# Game crashed! Crash report saved to: #@!@# C
```

**Comment by Dplayend** [comment]
fixed
